export default interface ListHorarioDetId {
    detHorarioId: number
    horarioId: number
    turnoId: number
    turno: string
    programaId: number
    programa: string
    periodoId: number
    anio: number
    mes: number
    tipEstudioId: number
	tipoEstudio: string
    seccion: string
    asiId: string
    nivel: number
    capacidad: number
    dia: number
    horaIni: string
    horaFin: string
    horaAcademica: string
    color: string
    observacion: string
    docenteId: number
    estado: number
    usuarioRegistra: string
    fechaRegistra: Date
    usuarioModifica: string
    fechaModifica: Date
    asignatura: string
    numDocTrabajador: string
    docente: string
}