export default interface ReporteSunedu {
    LocalCodigo: string
    ProgramaCodigo: string
    CodigoEstudiante: string
    EstudianteNombres: string
    Modalidad: string
    EntidadEmpresa: string
    ConvenioTipo: string
    ConvenioCodigo: string
    Programa: string
    PracticaTipo: string
    PracticasNivel: string
    FechaInicio: string
    FechaTermino: string
    Semestre: string
    Anio: number
    Facultad: string
    ProgramaDuracion: string
    PlanCurricularHoras: string
    PracticasCiclo: string
    EstudiantePlan: string
    PreguntaPertenece: string
    PreguntaDebe: string
    DocenteNombre: string
    EmpresaRazonSocial: string
    EmpresaTipo: string
    EmpresaRuc: string
    EmpresaDireccion: string
    Distrito: string
    Provincia: string
    Departamento: string
    RepresentanteLegalNombres: string
    RepresentanteCargo: string
    RepresentanteTelefono: string
    RepresentanteCorreo: string
    PracticaArea: string
    PracticaFechaInicio: string
    PracticaFechaFinal: string
    PracticaHorario: string
    Calificacion: string
    Condicion: string
    DocenteMailInstitucional: string
    DocenteTelefono: string
    EstudianteMailInstitucional: string
    AsignaturaCodigo: string
    AsignaturaNombre: string
}